from pathlib import Path
import json

def replace(path: str, old: str, new: str, count: int=1):
    target = Path(path)
    text = target.read_text(encoding='utf-8')
    actual = text.count(old)
    if actual < count:
        raise SystemExit(f'{path}: expected at least {count} occurrence(s), found {actual}: {old[:140]!r}')
    target.write_text(text.replace(old, new, count), encoding='utf-8')
replace('src/features/globe/GlobeViewport.tsx', '  naturalEvents: NaturalEventRecord[];\n  naturalEventsEnabled: boolean;', '  naturalEvents: NaturalEventRecord[];\n  naturalEventsEnabled: boolean;\n  weatherEnabled: boolean;\n  weatherSettings: WeatherLayerSettings;\n  weatherStorms: NaturalEventRecord[];', 1)
replace('src/features/globe/GlobeViewport.tsx', '  onObserverPasses?: (forecast: ObserverPassForecast | null) => void;', '  onObserverPasses?: (forecast: ObserverPassForecast | null) => void;\n  onAtmosphereStatus?: (status: AtmosphereStatus) => void;', 1)
replace('src/features/globe/GlobeViewport.tsx', '  const seismicRef = useRef<SeismicRenderer | null>(null);', '  const atmosphereRef = useRef<AtmosphereRenderer | null>(null);\n  const seismicRef = useRef<SeismicRenderer | null>(null);', 1)
replace('src/features/globe/GlobeViewport.tsx', '    captureStream: (fps = 30) => engineRef.current?.captureStream(fps) ?? null,\n  }), []);', '    captureStream: (fps = 30) => engineRef.current?.captureStream(fps) ?? null,\n    refreshAtmosphere: () => atmosphereRef.current?.refresh(),\n  }), []);', 1)
replace('src/features/globe/GlobeViewport.tsx', '  useEffect(() => { naturalEventsRef.current?.setSelected(props.selectedEntityId); }, [props.selectedEntityId]);\n\n  useEffect(() => { auroraRef.current?.setModel(props.auroraModel);', '  useEffect(() => { naturalEventsRef.current?.setSelected(props.selectedEntityId); }, [props.selectedEntityId]);\n  useEffect(() => { atmosphereRef.current?.setEnabled(props.weatherEnabled); }, [props.weatherEnabled]);\n  useEffect(() => { atmosphereRef.current?.setSettings(props.weatherSettings); }, [props.weatherSettings]);\n  useEffect(() => { atmosphereRef.current?.setStormEvents(props.weatherStorms); }, [props.weatherStorms]);\n\n  useEffect(() => { auroraRef.current?.setModel(props.auroraModel);', 1)
replace('src/features/globe/GlobeViewport.tsx', '    const earth = new EarthRenderer({ getSimulationTime: () => callbacksRef.current.getSimulationTime(), getVisualMode: () => callbacksRef.current.visualMode });\n    const aurora = new AuroraRenderer', '    const earth = new EarthRenderer({ getSimulationTime: () => callbacksRef.current.getSimulationTime(), getVisualMode: () => callbacksRef.current.visualMode });\n    const atmosphere = new AtmosphereRenderer({ getSimulationTime: () => callbacksRef.current.getSimulationTime(), onStatus: (status) => callbacksRef.current.onAtmosphereStatus?.(status) });\n    const aurora = new AuroraRenderer', 1)
replace('src/features/globe/GlobeViewport.tsx', '    engineRef.current = engine;\n    seismicRef.current = seismic;', '    engineRef.current = engine;\n    atmosphereRef.current = atmosphere;\n    seismicRef.current = seismic;', 1)
replace('src/features/globe/GlobeViewport.tsx', '      engine.registerRenderer(earth);\n      engine.registerRenderer(aurora);', '      engine.registerRenderer(earth);\n      engine.registerRenderer(atmosphere);\n      engine.registerRenderer(aurora);', 1)
replace('src/features/globe/GlobeViewport.tsx', '      seismic.setReducedMotion(callbacksRef.current.reducedMotion);', '      atmosphere.setEnabled(callbacksRef.current.weatherEnabled);\n      atmosphere.setSettings(callbacksRef.current.weatherSettings);\n      atmosphere.setStormEvents(callbacksRef.current.weatherStorms);\n      seismic.setReducedMotion(callbacksRef.current.reducedMotion);', 1)
replace('src/features/globe/GlobeViewport.tsx', '      seismicRef.current = null; naturalEventsRef.current = null; orbitRef.current = null; auroraRef.current = null; observerRef.current = null; orbitClientRef.current = null; engineRef.current = null;', '      atmosphereRef.current = null; seismicRef.current = null; naturalEventsRef.current = null; orbitRef.current = null; auroraRef.current = null; observerRef.current = null; orbitClientRef.current = null; engineRef.current = null;', 1)
