from pathlib import Path
import json

def replace(path: str, old: str, new: str, count: int=1):
    target = Path(path)
    text = target.read_text(encoding='utf-8')
    actual = text.count(old)
    if actual < count:
        raise SystemExit(f'{path}: expected at least {count} occurrence(s), found {actual}: {old[:140]!r}')
    target.write_text(text.replace(old, new, count), encoding='utf-8')
replace('src/app/App.tsx', "import { buildNowSignals, type NowSignal } from '../features/now/ranking';", "import { buildNowSignals, type NowSignal } from '../features/now/ranking';\nimport { DEFAULT_WEATHER_SETTINGS, EMPTY_ATMOSPHERE_STATUS, type AtmosphereStatus, type WeatherLayerSettings } from '../features/weather/types';", 1)
replace('src/app/App.tsx', '  const [auroraHemispheres, setAuroraHemispheres] = useState<AuroraHemispheres>(initialShareRef.current?.auroraHemispheres ?? { north: true, south: true });\n\n  const [observerLocation,', '  const [auroraHemispheres, setAuroraHemispheres] = useState<AuroraHemispheres>(initialShareRef.current?.auroraHemispheres ?? { north: true, south: true });\n  const [atmosphereSettings, setAtmosphereSettings] = useState<WeatherLayerSettings>(initialShareRef.current?.weatherSettings ?? { ...DEFAULT_WEATHER_SETTINGS });\n  const [atmosphereStatus, setAtmosphereStatus] = useState<AtmosphereStatus>(() => ({\n    clouds: { ...EMPTY_ATMOSPHERE_STATUS.clouds },\n    precipitation: { ...EMPTY_ATMOSPHERE_STATUS.precipitation },\n  }));\n\n  const [observerLocation,', 1)
replace('src/app/App.tsx', '    if (!appState.layers.events && !nowActive) return undefined;', '    if (!appState.layers.events && !nowActive && !(appState.layers.weather && atmosphereSettings.stormTracks)) return undefined;', 1)
replace('src/app/App.tsx', '  }, [appState.layers.events, naturalEventRefresh, emit, nowActive, pushToast]);', '  }, [appState.layers.events, appState.layers.weather, atmosphereSettings.stormTracks, naturalEventRefresh, emit, nowActive, pushToast]);', 1)
replace('src/app/App.tsx', '  useVisibilityAwareInterval(() => setNaturalEventRefresh((current) => ({ seq: current.seq + 1, force: false })), EONET_CACHE_POLICY.ttlMs, appState.layers.events || nowActive, { runOnVisible: true });', '  useVisibilityAwareInterval(() => setNaturalEventRefresh((current) => ({ seq: current.seq + 1, force: false })), EONET_CACHE_POLICY.ttlMs, appState.layers.events || nowActive || (appState.layers.weather && atmosphereSettings.stormTracks), { runOnVisible: true });', 1)
replace('src/app/App.tsx', '      auroraHemispheres,\n    };', '      auroraHemispheres,\n      weatherSettings: atmosphereSettings,\n    };', 1)
replace('src/app/App.tsx', '  }, [activeNaturalEventCategories, activeOrbitCategories, appState.clock, appState.layers, appState.selection.selectedId, appState.visualMode, auroraHemispheres, earthquakeMagnitude, earthquakeWindow, orbitScaleMode, orbitTrailMode, pointOfView, pushToast, showGroundTrack, showOrbitPath]);', '  }, [activeNaturalEventCategories, activeOrbitCategories, appState.clock, appState.layers, appState.selection.selectedId, appState.visualMode, atmosphereSettings, auroraHemispheres, earthquakeMagnitude, earthquakeWindow, orbitScaleMode, orbitTrailMode, pointOfView, pushToast, showGroundTrack, showOrbitPath]);', 1)
replace('src/app/App.tsx', "      const layers: LayerId[] = ['earthquakes', 'events', 'orbit', 'aurora'];", "      const layers: LayerId[] = ['weather', 'earthquakes', 'events', 'orbit', 'aurora'];", 1)
replace('src/app/App.tsx', '  const earthquakePanelProps = {', "  const atmospherePanelProps = {\n    settings: atmosphereSettings,\n    status: atmosphereStatus,\n    simulationTime,\n    timeMode: appState.clock?.mode ?? 'live' as const,\n    onSettingsChange: setAtmosphereSettings,\n    onRefresh: () => viewportRef.current?.refreshAtmosphere(),\n  };\n\n  const earthquakePanelProps = {", 1)
replace('src/app/App.tsx', '          naturalEvents={categoryFilteredNaturalEvents}\n          naturalEventsEnabled={appState.layers.events}\n          activeNaturalEventCategories={activeNaturalEventCategories}', '          naturalEvents={categoryFilteredNaturalEvents}\n          naturalEventsEnabled={appState.layers.events}\n          weatherEnabled={appState.layers.weather}\n          weatherSettings={atmosphereSettings}\n          weatherStorms={weatherStormEvents}\n          activeNaturalEventCategories={activeNaturalEventCategories}', 1)
replace('src/app/App.tsx', '          onObserverPasses={setObserverPassForecast}\n          onCameraState={handleCameraState}', '          onObserverPasses={setObserverPassForecast}\n          onAtmosphereStatus={setAtmosphereStatus}\n          onCameraState={handleCameraState}', 1)
replace('src/app/App.tsx', '<LayerPanel layers={appState.layers} earthquake={earthquakePanelProps}', '<LayerPanel layers={appState.layers} weather={atmospherePanelProps} earthquake={earthquakePanelProps}', 1)
replace('src/app/App.tsx', '<LayerPanel compact layers={appState.layers} earthquake={earthquakePanelProps}', '<LayerPanel compact layers={appState.layers} weather={atmospherePanelProps} earthquake={earthquakePanelProps}', 1)
replace('src/app/App.tsx', '  const naturalEvents = naturalEventSnapshot?.data.events ?? [];\n  const simulationTime', "  const naturalEvents = naturalEventSnapshot?.data.events ?? [];\n  const weatherStormEvents = useMemo(() => naturalEvents.filter((event) => event.category === 'severe-storm'), [naturalEvents]);\n  const simulationTime", 1)
replace('src/tests/share-state.test.ts', '  layers: { earthquakes: true, events: false, orbit: true, aurora: true },', '  layers: { weather: true, earthquakes: true, events: false, orbit: true, aurora: true },', 1)
replace('src/tests/share-state.test.ts', "  clock: { mode: 'simulation',", "  weatherSettings: { clouds: true, precipitation: true, stormTracks: false, opacity: 0.65 },\n  clock: { mode: 'simulation',", 1)
replace('src/tests/share-state.test.ts', '    expect(parsed.layers?.events).toBe(false);', '    expect(parsed.layers?.events).toBe(false);\n    expect(parsed.layers?.weather).toBe(true);\n    expect(parsed.weatherSettings).toEqual({ clouds: true, precipitation: true, stormTracks: false, opacity: 0.65 });', 1)
replace('src/tests/search-commands.test.ts', "    expect(parseCommand('show earthquakes')?.intent).toEqual({ type: 'layer', operation: 'show', layer: 'earthquakes' });\n    expect(parseCommand('only GPS')?.intent)", "    expect(parseCommand('show earthquakes')?.intent).toEqual({ type: 'layer', operation: 'show', layer: 'earthquakes' });\n    expect(parseCommand('show clouds')?.intent).toEqual({ type: 'layer', operation: 'show', layer: 'weather' });\n    expect(parseCommand('show weather')?.intent).toEqual({ type: 'satellite-category', operation: 'show', category: 'weather' });\n    expect(parseCommand('only GPS')?.intent)", 1)
replace('src/app/version.ts', "export const APP_VERSION = '1.1.0';", "export const APP_VERSION = '1.2.0';", 1)
